[package]
name = "programify-feature-gate"
version = "0.1.0"
edition = "2021"

[dependencies]
base64 = "0.21.7"
clap = { version = "4.0.29", features = ["derive"] }
dotenv = "0.15.0"
serde = { version = "1.0.195", features = ["derive"] }
serde_json = "1.0.111"
solana-client = "1.18.0"
solana-sdk = "1.18.0"
solana-transaction-status = "1.18.0"
tokio = { version = "1", features = ["full"] }
